### ISSUE TITLE
Including css require postcss-import because of .postcssrc.js

### ISSUE THREAD

**Issue by doits** [keen-on-design/vue-flash-message#17]
When I try to include the basic styles (`vue-flash-message/dist/vue-flash-message.min.css`) it complains that it cannot find `postcss-import` and I should install it. I traced it down to the `.postcssrc.js` under `node_modules/vue-flash-message/.postcssrc.js` – it seems by importing the styles postcss traverses up until it finds a config and tries to use this.

It should of course only use my own postcss config. I think you should exclude the postcss config from bundling, since it should not be needed when using this as a plugin.

**Comment by doits** [comment]
The error is:

```
error  in ./node_modules/vue-flash-message/dist/vue-flash-message.min.css

Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-import'

(@/Users/markus/svn/ats/frontend/node_modules/vue-flash-message/.postcssrc.js)
    at load (/Users/markus/svn/ats/frontend/node_modules/postcss-load-config/src/plugins.js:21:13)
    at Object.keys.filter.map (/Users/markus/svn/ats/frontend/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/Users/markus/svn/ats/frontend/node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (/Users/markus/svn/ats/frontend/node_modules/postcss-load-config/src/index.js:72:18)
```

I don't think the plugin should mess with the postcss config. I think it is because of the [config cascade](https://github.com/postcss/postcss-loader#config-cascade).

**Comment by keen-on-design** [comment]
Fixed that. Thank you!
